import {
    Conversation,
    ConversationContent,
    ConversationScrollButton,
} from "@/components/ai-elements/conversation";
import {
    Message,
    MessageContent,
    MessageResponse,
} from "@/components/ai-elements/message";
import {
    Reasoning,
    ReasoningTrigger,
    ReasoningContent,
} from "@/components/ai-elements/reasoning";
import type { UIMessage, ChatStatus } from "ai";

interface MessageListProps {
    messages: UIMessage[];
    reasoningEnabled?: boolean;
    chatStatus?: ChatStatus;
}

function parseMessageContent(message: UIMessage) {
    if (!message.parts) {
        return {
            reasoningText: "",
            textContent: "",
        };
    }

    const nativeReasoning = message.parts
        .filter((p) => p.type === "reasoning")
        .map((p) => (p as { text?: string }).text)
        .join("");

    const textContent = message.parts
        .filter((p) => p.type === "text")
        .map((p) => (p as { text?: string }).text)
        .join("");

    // Regex fallback to extract <think>...</think> from textContent
    let fallbackReasoning = "";
    const thinkRegex = /<think>([\s\S]*?)(<\/think>|$)/gi;
    let match;
    
    while ((match = thinkRegex.exec(textContent)) !== null) {
        fallbackReasoning += match[1];
    }

    // Remove <think>...</think> from textContent so it isn't rendered as final response
    const cleanTextContent = textContent.replace(/<think>[\s\S]*?(<\/think>|$)/gi, "");

    const reasoningText = (nativeReasoning + fallbackReasoning).trim();

    return {
        reasoningText,
        textContent: cleanTextContent,
    };
}

export const MessageList = ({ messages, reasoningEnabled = true, chatStatus }: MessageListProps) => {
    return (
        <Conversation>
            <ConversationContent>
                {messages.map((message, index) => {
                    const isAssistant = message.role === "assistant";
                    const isLastMessage = index === messages.length - 1;
                    const isStreaming = isLastMessage && chatStatus === "streaming";
                    
                    const { reasoningText, textContent } = parseMessageContent(message);

                    return (
                        <Message
                            from={message.role === "user" ? "user" : "assistant"}
                            key={message.id}
                        >
                            <div>
                                <MessageContent>
                                    {isAssistant && reasoningEnabled && (
                                        <>
                                            {(reasoningText || isStreaming) ? (
                                                <Reasoning isStreaming={isStreaming}>
                                                    <ReasoningTrigger />
                                                    <ReasoningContent>{reasoningText}</ReasoningContent>
                                                </Reasoning>
                                            ) : (
                                                <Reasoning defaultOpen={false}>
                                                    <ReasoningTrigger getThinkingMessage={() => <p>No reasoning found</p>} />
                                                    <ReasoningContent>No reasoning was generated by the model.</ReasoningContent>
                                                </Reasoning>
                                            )}
                                        </>
                                    )}
                                    <MessageResponse>
                                        {textContent}
                                    </MessageResponse>
                                </MessageContent>
                            </div>
                        </Message>
                    );
                })}
            </ConversationContent>
            <ConversationScrollButton />
        </Conversation>
    );
};

