import {
    Conversation,
    ConversationContent,
    ConversationScrollButton,
} from "@/components/ai-elements/conversation";
import {
    Message,
    MessageContent,
    MessageResponse,
} from "@/components/ai-elements/message";
import {
    Reasoning,
    ReasoningTrigger,
    ReasoningContent,
} from "@/components/ai-elements/reasoning";
import { Shimmer } from "@/components/ai-elements/shimmer";
import type { UIMessage, ChatStatus } from "ai";

interface MessageListProps {
    messages: UIMessage[];
    reasoningEnabled?: boolean;
    chatStatus?: ChatStatus;
}

function parseMessageContent(message: UIMessage) {
    let nativeReasoning = "";
    let rawText = "";

    if (Array.isArray(message.parts) && message.parts.length > 0) {
        nativeReasoning = message.parts
            .filter((p) => p.type === "reasoning")
            .map((p) => (p as { text?: string; reasoning?: string }).text || (p as { reasoning?: string }).reasoning || "")
            .join("");

        rawText = message.parts
            .filter((p) => p.type === "text")
            .map((p) => (p as { text?: string }).text || "")
            .join("");
    } else {
        rawText = (message as any).content || "";
    }

    // Regex fallback to extract <think>...</think> from text content
    let fallbackReasoning = "";
    const thinkRegex = /<think>([\s\S]*?)(<\/think>|$)/gi;
    let match;
    
    while ((match = thinkRegex.exec(rawText)) !== null) {
        fallbackReasoning += match[1];
    }

    // Remove <think>...</think> from text content so it isn't rendered twice
    const cleanTextContent = rawText.replace(/<think>[\s\S]*?(<\/think>|$)/gi, "").trim();
    const reasoningText = (nativeReasoning + fallbackReasoning).trim();

    return {
        reasoningText,
        textContent: cleanTextContent,
    };
}

export const MessageList = ({ messages, reasoningEnabled = true, chatStatus }: MessageListProps) => {
    return (
        <Conversation>
            <ConversationContent>
                {messages.map((message, index) => {
                    const isAssistant = message.role === "assistant";
                    const isLastMessage = index === messages.length - 1;
                    const isStreaming = isLastMessage && chatStatus === "streaming";
                    
                    const { reasoningText, textContent } = parseMessageContent(message);

                    const isWaiting = isAssistant && isLastMessage && (chatStatus === "submitted" || (chatStatus === "streaming" && !reasoningText && !textContent));

                    return (
                        <Message
                            from={message.role === "user" ? "user" : "assistant"}
                            key={message.id}
                        >
                            <div>
                                <MessageContent>
                                    {isWaiting ? (
                                        <Shimmer className="text-sm" duration={2}>
                                            Thinking…
                                        </Shimmer>
                                    ) : (
                                        <>
                                            {isAssistant && reasoningEnabled && (
                                                <>
                                                    {(reasoningText || isStreaming) ? (
                                                        <Reasoning isStreaming={isStreaming}>
                                                            <ReasoningTrigger />
                                                            <ReasoningContent>{reasoningText}</ReasoningContent>
                                                        </Reasoning>
                                                    ) : (
                                                        <Reasoning defaultOpen={false}>
                                                            <ReasoningTrigger getThinkingMessage={() => <p>No reasoning found</p>} />
                                                            <ReasoningContent>No reasoning was generated by the model.</ReasoningContent>
                                                        </Reasoning>
                                                    )}
                                                </>
                                            )}
                                            <MessageResponse>
                                                {textContent}
                                            </MessageResponse>
                                        </>
                                    )}
                                </MessageContent>
                            </div>
                        </Message>
                    );
                })}
            </ConversationContent>
            <ConversationScrollButton />
        </Conversation>
    );
};

